# 余裕できたら以下のフォルダにそれぞれ設定を書いていきたい
# inherit_from:
#   - config/rubocop/rubocop.yml
#   - config/rubocop/rails.yml
#   - config/rubocop/rspec.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  # 除外
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  DisplayCopNames: true
  TargetRubyVersion: 3.0.2

Rails:
  Enabled: true

##################### Style ##################################

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# ダブルクオーテーションに統一
Style/StringLiterals:
  EnforcedStyle: double_quotes

# ローカル変数とメソッドの呼び出しの区別をつける
Style/RedundantSelf:
  Enabled: false

##################### Layout ##################################

# private/protected は一段深くインデントする
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

##################### Metrics ##################################

# メソッド名の長さを最長20文字に
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

##################### Metrics ##################################

# 3文字未満だと指摘される設定を無効
Naming/MethodParameterName:
  Enabled: false
